#!/usr/bin/env python3
###############################################################################
# NAME:             cretan-daemon
#
# AUTHOR:           Ethan D. Twardy <edtwardy@mtu.edu>
#
# DESCRIPTION:      The Cretan Daemon
#
# CREATED:          06/01/2020
#
# LAST EDITED:      06/01/2020
###

import asyncio
from cretan import Daemon

if __name__ == '__main__':
    asyncio.run(Daemon.main())

###############################################################################
